-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 23:19:26 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema CQUPT
-- -----------------------------------------------------
-- Academies,Classes and Students of CQUPT

-- -----------------------------------------------------
-- Schema CQUPT
--
-- Academies,Classes and Students of CQUPT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CQUPT` DEFAULT CHARACTER SET utf8 ;
USE `CQUPT` ;

-- -----------------------------------------------------
-- Table `CQUPT`.`ACADEMY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CQUPT`.`ACADEMY` (
  `Software Engineering` INT NOT NULL COMMENT '软件工程学院',
  `Computer Science and Technology` INT NOT NULL COMMENT '计算机科学与技术学院',
  `Automation Engineering` INT NOT NULL COMMENT '自动化工程学院',
  PRIMARY KEY (`Software Engineering`, `Computer Science and Technology`, `Automation Engineering`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CQUPT`.`CLASS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CQUPT`.`CLASS` (
  `Excellent Engineer Class` INT NOT NULL COMMENT '卓越工程师班',
  `Feature Class` INT NOT NULL COMMENT '特色班',
  `Broad Heading Class` INT NOT NULL COMMENT '大类班',
  `ACADEMY_Software Engineering` INT NOT NULL,
  `ACADEMY_Computer Science and Technology` INT NOT NULL,
  `ACADEMY_Automation Engineering` INT NOT NULL,
  PRIMARY KEY (`Excellent Engineer Class`, `Feature Class`, `Broad Heading Class`, `ACADEMY_Software Engineering`, `ACADEMY_Computer Science and Technology`, `ACADEMY_Automation Engineering`),
  INDEX `fk_CLASS_ACADEMY_idx` (`ACADEMY_Software Engineering` ASC, `ACADEMY_Computer Science and Technology` ASC, `ACADEMY_Automation Engineering` ASC) VISIBLE,
  CONSTRAINT `fk_CLASS_ACADEMY`
    FOREIGN KEY (`ACADEMY_Software Engineering` , `ACADEMY_Computer Science and Technology` , `ACADEMY_Automation Engineering`)
    REFERENCES `CQUPT`.`ACADEMY` (`Software Engineering` , `Computer Science and Technology` , `Automation Engineering`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CQUPT`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CQUPT`.`STUDENT` (
  `Freshman` INT NOT NULL COMMENT '大一学生',
  `Sophomore` INT NOT NULL COMMENT '大二学生',
  `Junior` INT NOT NULL COMMENT '大三学生',
  `Senior` INT NOT NULL COMMENT '大四学生',
  `Graduate` INT NOT NULL COMMENT '研究生',
  `CLASS_Excellent Engineer Class` INT NOT NULL,
  `CLASS_Feature Class` INT NOT NULL,
  `CLASS_Broad Heading Class` INT NOT NULL,
  `CLASS_ACADEMY_Software Engineering` INT NOT NULL,
  `CLASS_ACADEMY_Computer Science and Technology` INT NOT NULL,
  `CLASS_ACADEMY_Automation Engineering` INT NOT NULL,
  PRIMARY KEY (`Freshman`, `Sophomore`, `Junior`, `Senior`, `Graduate`, `CLASS_Excellent Engineer Class`, `CLASS_Feature Class`, `CLASS_Broad Heading Class`, `CLASS_ACADEMY_Software Engineering`, `CLASS_ACADEMY_Computer Science and Technology`, `CLASS_ACADEMY_Automation Engineering`),
  INDEX `fk_STUDENT_CLASS1_idx` (`CLASS_Excellent Engineer Class` ASC, `CLASS_Feature Class` ASC, `CLASS_Broad Heading Class` ASC, `CLASS_ACADEMY_Software Engineering` ASC, `CLASS_ACADEMY_Computer Science and Technology` ASC, `CLASS_ACADEMY_Automation Engineering` ASC) VISIBLE,
  CONSTRAINT `fk_STUDENT_CLASS1`
    FOREIGN KEY (`CLASS_Excellent Engineer Class` , `CLASS_Feature Class` , `CLASS_Broad Heading Class` , `CLASS_ACADEMY_Software Engineering` , `CLASS_ACADEMY_Computer Science and Technology` , `CLASS_ACADEMY_Automation Engineering`)
    REFERENCES `CQUPT`.`CLASS` (`Excellent Engineer Class` , `Feature Class` , `Broad Heading Class` , `ACADEMY_Software Engineering` , `ACADEMY_Computer Science and Technology` , `ACADEMY_Automation Engineering`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
